CREATE DATABASE IF NOT EXISTS dummyjson_db;
USE dummyjson_db;

CREATE TABLE users (
    id INT PRIMARY KEY AUTO_INCREMENT, 
    first_name VARCHAR(100) NOT NULL,
    last_name VARCHAR(100) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    username VARCHAR(100) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL
);

